In [3]:
# from skittles import SkittlesEasy, SkittlesMedium, SkittlesHard
# from typing import Any, Dict, Optional, Tuple, Union
#
# import chex
# from flax import struct
# import jax
# from jax import lax
# import jax.numpy as jnp
#
# from gymnax.environments import environment
# from gymnax.environments import spaces
# import matplotlib.pyplot as plt
#
# # env = SkittlesHard(obs_size=256)
# # env_params = env.default_params
# # obs, state = env.reset(jax.random.PRNGKey(0), env_params)
# # key = jax.random.PRNGKey(0)
# # # plt.imshow(obs)
# # # plt.axis("off")
# # # plt.show()
#
# # while True:
# #     action = int(input("Input: 0,1,2,3,4"))
# #     key, step_key = jax.random.split(key)
# #     obs, state, reward, done, info = env.step(step_key, state, action)
# #     print(state.matrix_state, state.x)
# #     # plt.imshow(obs)
# #     # plt.axis("off")
# #     # plt.show()
#
#
#
# #     # if done:
# #         # break
#
# import jax
# import pygame
# import numpy as np
#
# # Change these to play other games
# ENV_NAME = "SkittlesHard"
# IS_POMDP = False
# OBS_SIZE = 256
#
# def to_surf(arr):
#     # Convert jax arry to pygame surface
#     return np.transpose(np.array(observation * 255).astype(np.uint8), (1, 0, 2))
#
#
# # Create env env variant
# env = SkittlesMedium(obs_size=OBS_SIZE, partial_obs = IS_POMDP)
# env_params = env.default_params
# # Vectorize and compile the env
# env_reset = jax.jit(env.reset)
# env_step = jax.jit(env.step)
#
# # Initialize environment
# key = jax.random.PRNGKey(0)
# key, reset_key = jax.random.split(key)
# observation, env_state = env_reset(reset_key, env_params)
# done = False
#
# # Pygame setup
# pygame.init()
# screen = pygame.display.set_mode((OBS_SIZE, OBS_SIZE))
# clock = pygame.time.Clock()
# running = True
#
# # Convert numpy array to Pygame surface
# surface = pygame.surfarray.make_surface(to_surf(observation))
#
# # Action mappings (modify based on your environment's action space)
# ACTION_MEANINGS = {
#     pygame.K_UP: 0,
#     pygame.K_DOWN: 1,
#     pygame.K_LEFT: 2,
#     pygame.K_RIGHT: 3,
#     pygame.K_SPACE: 4,
#     # Add more keys if needed
# }
# print("Controls: up, down, left, right, spacebar")
#
#
#
#
# while running:
#     # Handle events
#     action = None
#     for event in pygame.event.get():
#         if event.type == pygame.QUIT:
#             running = False
#         elif event.type == pygame.KEYDOWN:
#             if event.key in ACTION_MEANINGS:
#                 action = ACTION_MEANINGS[event.key]
#
#
#     # Render to screen
#     screen.blit(surface, (0, 0))
#     pygame.display.flip()
#
#     # Take action if key pressed
#     if action is not None:
#         key, step_key = jax.random.split(key)
#         observation, env_state, reward, done, info = env_step(step_key, env_state, action, env_params)
#         surface = pygame.surfarray.make_surface(to_surf(observation))
#
#         # Render to screen
#         if done:
#             print("Game over")
#             break
#
#     clock.tick(30)  # Control FPS
#
# pygame.quit()


Controls: up, down, left, right, spacebar


In [7]:
import jax.random
import optax

schedule = optax.linear_schedule(
    init_value=1.0,
    end_value=0,
    transition_steps=200000,
)

print(schedule(1))

print(schedule(10))
print(schedule(200000-1))

0.999995
0.99995
5.00679e-06


In [1]:
from skittles import SkittlesEasy
import jax

env = SkittlesEasy(partial_obs=False)
obs, state = env.reset(jax.random.PRNGKey(0), env.default_params)
action = 2
obs, state, reward, done, info = env.step(jax.random.PRNGKey(1), state, action, env.default_params)
action = 3
obs, state, reward, done, info = env.step(jax.random.PRNGKey(2), state, action, env.default_params)
action = 4
obs, state, reward, done, info = env.step(jax.random.PRNGKey(3), state, action, env.default_params)
print(obs)


[[0 0 0 0 0 1 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 2 0]]
